"use client";

import { useEffect, useState } from "react";
import type { ScheduleVariant } from "@/types/schedule";
import { Card, Button, Input } from "@/components/ui";
import { DegreeProgress } from "@/components/degree-progress";

const PREFS_KEY = "coursehorse.schedulePrefs";

type Prefs = {
  school: string;
  majors: string;
  gradDate: string;
};

const defaultPrefs: Prefs = { school: "", majors: "", gradDate: "" };

type Props = {
  scheduleVariant: ScheduleVariant;
  onScheduleVariantChange: (v: ScheduleVariant) => void;
  onSaveExperimentalAsSaved: () => void;
  onClearSavedOverride: () => void;
  onRegenerateExperimental: () => void;
  hasSavedOverride: boolean;
  totalCredits: number;
};

export function ScheduleOptionsPanel({
  scheduleVariant,
  onScheduleVariantChange,
  onSaveExperimentalAsSaved,
  onClearSavedOverride,
  onRegenerateExperimental,
  hasSavedOverride,
  totalCredits,
}: Props) {
  const [prefs, setPrefs] = useState<Prefs>(defaultPrefs);
  const [savedMsg, setSavedMsg] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(PREFS_KEY);
      if (!raw) return;
      const parsed = JSON.parse(raw) as Partial<Prefs>;
      const next = { ...defaultPrefs, ...parsed };
      queueMicrotask(() => setPrefs(next));
    } catch { /* ignore */ }
  }, []);

  function persist(next: Prefs) {
    setPrefs(next);
    try {
      localStorage.setItem(PREFS_KEY, JSON.stringify(next));
      setSavedMsg(true);
      window.setTimeout(() => setSavedMsg(false), 2000);
    } catch { /* ignore */ }
  }

  return (
    <aside className="w-full shrink-0 lg:sticky lg:top-24 lg:w-80">
      <div className="space-y-4">
        <Card className="flex items-center justify-center p-5">
          <DegreeProgress completed={totalCredits} required={120} size="sm" />
        </Card>

        <Card>
          <h2 className="text-sm font-semibold text-stone-900">Schedule options</h2>
          <p className="mt-0.5 text-xs text-stone-500">
            Stored on this device for now.
          </p>
          <div className="mt-4 space-y-3">
            <Input
              id="school"
              label="School"
              value={prefs.school}
              onChange={(e) => persist({ ...prefs, school: e.target.value })}
              placeholder="e.g. State University"
            />
            <Input
              id="majors"
              label="Major(s)"
              value={prefs.majors}
              onChange={(e) => persist({ ...prefs, majors: e.target.value })}
              placeholder="e.g. Computer Science, Math"
            />
            <Input
              id="grad"
              label="Expected graduation"
              type="date"
              value={prefs.gradDate}
              onChange={(e) => persist({ ...prefs, gradDate: e.target.value })}
              hint="mm/dd/yyyy"
            />
          </div>

          <div className="mt-5 border-t border-stone-100 pt-4">
            <p className="text-xs font-medium text-stone-700">Active schedule</p>
            <div className="mt-2 grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => onScheduleVariantChange("saved")}
                className={`rounded-[var(--radius-button)] px-3 py-2 text-sm font-medium transition ${
                  scheduleVariant === "saved"
                    ? "bg-amber-100 text-amber-950 ring-1 ring-amber-300"
                    : "bg-stone-50 text-stone-700 ring-1 ring-stone-200 hover:bg-stone-100"
                }`}
              >
                Saved
              </button>
              <button
                type="button"
                onClick={() => onScheduleVariantChange("experimental")}
                className={`rounded-[var(--radius-button)] px-3 py-2 text-sm font-medium transition ${
                  scheduleVariant === "experimental"
                    ? "bg-sky-100 text-sky-950 ring-1 ring-sky-300"
                    : "bg-stone-50 text-stone-700 ring-1 ring-stone-200 hover:bg-stone-100"
                }`}
              >
                Experimental
              </button>
            </div>
            <div className="mt-2 text-[11px] leading-relaxed text-stone-500">
              {scheduleVariant === "saved"
                ? "Your locked-in plan."
                : "Generated by the optimizer — explore without saving."}
            </div>
            {scheduleVariant === "experimental" ? (
              <div className="mt-3 space-y-2">
                <Button className="w-full" onClick={onSaveExperimentalAsSaved}>
                  Save as my plan
                </Button>
                <Button variant="secondary" className="w-full" size="sm" onClick={onRegenerateExperimental}>
                  Regenerate
                </Button>
              </div>
            ) : null}
            {hasSavedOverride ? (
              <Button variant="ghost" className="mt-2 w-full" size="sm" onClick={onClearSavedOverride}>
                Revert to default
              </Button>
            ) : null}
          </div>

          {savedMsg ? (
            <p className="mt-3 text-center text-xs text-emerald-700">Options saved.</p>
          ) : null}
        </Card>
      </div>
    </aside>
  );
}
